name: Test Raccoon Post-Quantum Digital Signature Scheme

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set machine stack size
      run: sudo ulimit -s 65536 # 64kB
    - name: Setup Google-Test
      run: |
        pushd ~
        git clone https://github.com/google/googletest.git -b v1.14.0
        pushd googletest
        mkdir build
        pushd build
        cmake .. -DBUILD_GMOCK=OFF
        make
        sudo make install
        popd
        popd
        popd
    - name: Execute Tests on ${{matrix.os}}
      run: make -j
    - name: Execute Tests with AddressSanitizer on ${{matrix.os}}
      run: make asan_test -j
    - name: Execute Tests with UndefinedBehaviourSanitizer on ${{matrix.os}}
      run: make ubsan_test -j
