name: Test Raccoon Post-Quantum Digital Signature Scheme

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [g++, clang++]
        cxx_defs: [-DPREFER_INT128_COMPILER_EXTENSION_TYPE, '']
        build_type: [debug, release]
        test_type: ['standard', asan, ubsan]

    steps:
    - uses: actions/checkout@v4
    - name: Setup Google-Test
      run: |
        pushd ~
        git clone https://github.com/google/googletest.git -b v1.15.0
        pushd googletest
        mkdir build
        pushd build
        cmake .. -DBUILD_GMOCK=OFF
        make
        sudo make install
        popd
        popd
        popd
    - name: Execute Tests on ${{matrix.os}}, compiled with ${{matrix.compiler}}
      if: ${{matrix.test_type == 'standard'}}
      run: CXX=${{matrix.compiler}} CXX_DEFS=${{matrix.cxx_defs}} make -j

    - name: Execute Tests with ${{matrix.test_type}}, in ${{matrix.build_type}} mode, on Ubuntu, compiled with ${{matrix.compiler}}
      if: ${{matrix.os == 'ubuntu-latest' && matrix.test_type != 'standard'}}
      run: ulimit -s 65536 && CXX=${{matrix.compiler}} CXX_DEFS=${{matrix.cxx_defs}} make ${{matrix.build_type}}_${{matrix.test_type}}_test -j

    - name: Execute Tests with ${{matrix.test_type}}, in ${{matrix.build_type}} mode, on MacOS, compiled with ${{matrix.compiler}}
      if: ${{matrix.os == 'macos-latest' && matrix.test_type != 'standard'}}
      run: CXX=${{matrix.compiler}} CXX_DEFS=${{matrix.cxx_defs}} make ${{matrix.build_type}}_${{matrix.test_type}}_test -j
